
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_architecture }}.yml"
    - "../vars/empty.yml"

- include_vars:
    file: default.yml

- name: packages (debian)
  become: true
  ignore_errors: true
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  with_items:
    - rsync
    - cpio

- name: packages (centos)
  become: true
  ignore_errors: true
  yum:
    name: 'rsync'
  when: ansible_os_family == "RedHat"

- name: Get debian kernel
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "/boot/{{ item.name }}"
    checksum: ""
  with_items:
    - { url: "{{ debian_kernel }}", checksum: "{{ debian_kernel_sha }}", name: debian-kernel     }
    - { url: "{{ debian_initrd }}", checksum: "{{ debian_initrd_sha }}", name: debian-initrd.gz  }

- name: Add grub menu (debian)
  become: true
  template:
    src: grub/debian.j2
    dest: /etc/grub.d/15_debian_installer
    mode: 0755
  when: debian_grub and ansible_os_family == "Debian"
  notify: Update-grub

- name: Add grub menu (redhat)
  become: true
  template:
    src: grub/centos.j2
    dest: /etc/grub.d/15_debian_installer
    mode: 0755
  when: debian_grub and ansible_os_family == "RedHat"
  notify: Update-grub

- name: Prepare directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: debian_rebuild_initrd
  with_items:
    - /boot/preseed
    - /boot/preseed/etc/udev/rules.d
    - /boot/preseed/lib/debian-installer.d
    - /boot/preseed/usr/bin

- import_tasks: sshd.yml
  when: debian_rebuild_initrd

- import_tasks: preseed.yml
  when: debian_rebuild_initrd

- import_tasks: bond.yml
  when: debian_rebuild_initrd

- meta: flush_handlers

- block:
    - name: Save interfaces config
      fetch:
        src: /etc/network/interfaces
        dest: facts/interfaces-{{ inventory_hostname }}
        fail_on_missing: no
        flat: true
    - name: Save interfaces.d config
      synchronize:
        src: /etc/network/interfaces.d
        dest: facts/interfaces-{{ inventory_hostname }}.d
        mode: pull
        verify_host: false
      ignore_errors: true

- name: packages (debian)
  become: true
  apt:
    name: 'kexec-tools'
    update_cache: true
    cache_valid_time: 3600
  when: debian_kexec and ansible_os_family == "Debian"

- name: packages (centos)
  become: true
  yum:
    name: 'kexec-tools'
  when: debian_kexec and ansible_os_family == "RedHat"

- name: Run debian installer
  when: debian_kexec
  block:
    - name: Run sync
      become: true
      command: "sync"

    - name: Run kexec
      become: true
      command: "kexec {{ item }}"
      timeout: 30
      register: result
      failed_when: result.rc != 0
      with_items:
        - "-l /boot/debian-kernel --initrd=/boot/debian-initrd{{ '-preseed' if debian_rebuild_initrd }}.gz --append=\"{{ debian_cmdline }} {{ 'file=/debian-preseed.cfg' if debian_rebuild_initrd else debian_preseed_url }} {{ debian_cmdline_addon }}\""
        - "-e"

  rescue:
    - name: check server
      connection: local
      command: "ping -c 10 {{ ansible_default_ipv4['address'] }}"
      when: debian_kexec
